name: Run Android E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./wdio-appium-project
        run: npm ci

      - name: Download APK from GitHub Release
        run: |
          wget https://github.com/steviebdesignstraining/Stadion_Luton_Retail_WebdriverIO/releases/download/v1.0.0/Stadion.apk -O ./wdio-appium-project/app.apk

      - name: Install Appium globally
        run: npm install -g appium

      - name: Start Appium server in background
        run: |
          nohup appium --log ./wdio-appium-project/appium.log &
          sleep 10

      - name: Run WebdriverIO tests
        working-directory: ./wdio-appium-project
        run: |
          echo "Running E2E tests..."
          npx
